spring:
  application:
    name: assistant

# 多数据源配置
  datasource:
    dynamic:
      primary: mysql # 设置默认的数据源
      datasource:
        mysql: # MySQL数据源配置
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        oracle: # Oracle数据源配置
          url: jdbc:oracle:thin:@localhost:1521:ORCL
          username: system
          password: 123456
          driver-class-name: oracle.jdbc.OracleDriver

# MyBatis配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
